bic_enllac_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BicEnllacBundle:Default:index }

bic_enllac_annotation_import:
    resource: "@BicEnllacBundle/Controller/DefaultController.php"
    type:    annotation